### ISSUE TITLE
Unsupported attribute error

### ISSUE THREAD

**Issue by Adamsmith6300** [lgallard/terraform-aws-cognito-user-pool#18]
Hi there, I've been working with your module for over a month and am all of a sudden getting an 'unsupported attribute' error on admin_create_user_config.0.unused_account_validity_days

Does this have anything to do with AWS having deprecated that attribute?

Thanks!
![Capture+_2020-07-31-13-14-42](https://user-images.githubusercontent.com/20409524/89075127-58364a80-d332-11ea-85fe-f03fcc978858.png)

**Comment by lgallard** [comment]
Hi @Adamsmith6300,

In AWS provider version [3.0.0](https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v3.0.0). `unused_account_validity_days` was removed due to deprecation:

> resource/aws_cognito_user_pool: Remove deprecated admin_create_user_config configuration block unused_account_validity_days argument [(#14294](https://github.com/terraform-providers/terraform-provider-aws/pull/14294))

Version [2.4.9](https://github.com/terraform-providers/terraform-provider-aws/releases/tag/v2.49.0) already allow to omit this parameter:

> resource/aws_cognito_user_pool: Allow admin_create_user_config configuration block unused_account_validity_days argument to be omitted ([#12001](https://github.com/terraform-providers/terraform-provider-aws/pull/12001))

#12001 mentions the fact that the API would deprecate the field.

I would update the module and documentation to avoid confuntion.

Regards,

**Comment by lgallard** [comment]
@Adamsmith6300  I just released the module to version 0.5.0. Please checkout this version or current master, don't define  `unused_account_validity_days` and try again!

**Comment by Adamsmith6300** [comment]
Ok, I will try again. Thanks!

**Comment by Adamsmith6300** [comment]
Updated and worked just fine, thanks lgallard!

**Comment by lgallard** [comment]
@Adamsmith6300  you are welcome! Thanks for reporting the issue!
